### ISSUE TITLE
problematic css classes

### ISSUE THREAD

**Issue by JAnDud** [magnusmanske/listeria_rs#23] opened 2020-11-21 14:26 UTC
when page uses template for formatting otput, icluded styles breaks output:

https://cs.wikipedia.org/w/index.php?title=Wikipedie:WikiProjekt_Drobné_památky/okres_České_Budějovice/Boršov_nad_Vltavou&curid=1609407&diff=19182032&oldid=19116942&diffmode=source

please, don't include classses when  row_template = yes

**Comment by magnusmanske** [comment] 2021-01-26 11:07
Duplicate of #27

**Closed by magnusmanske** 2021-01-26 11:07 UTC
