### ISSUE TITLE
Q10905276 doesn't work

### ISSUE THREAD

**Issue by grimes2** [magnusmanske/listeria_rs#133] opened 2024-10-05 12:14 UTC
My query doesn't work:
{{Wikidata list
|sparql=SELECT ?item
WHERE
{
  ?item wdt:P166 wd:Q10905276 . # Commander's Cross of the Order of Merit of the Federal Republic of Germany
  ?article_en schema:about ?item .
  ?article_en schema:isPartOf <https://en.wikipedia.org/>. # and has article in English
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en" }
}
|wdq=
|sort=P569
|columns=label:name,P18,description,P27,P569,P570,P19,P20,item
|section=
|thumb=120
|summary=itemnumber
}}
{{Wikidata list end}}

https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Awards/Commander%27s_Cross_of_the_Order_of_Merit_of_the_Federal_Republic_of_Germany_list
Whats wrong?

**Comment by pere-prlpz** [comment] 2024-10-06 20:55
I'd say you have a syntax error in your query. As it is, it doesn't work in Wikidata query service.

To fix it:

SELECT ?item
WHERE
{
?item wdt:P166 wd:Q10905276 . # Commander's Cross of the Order of Merit of the Federal Republic of Germany
?article_en schema:about ?item .
?article_en schema:isPartOf https://en.wikipedia.org/. # and has article in English
SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en" }
}

And in general, I'd suggest testing the queries in WQS first, and asking at https://www.wikidata.org/wiki/Wikidata:Request_a_query  in case of problems with the query. You will get answers a lot earlier - and probably better answers, too.

**Comment by pere-prlpz** [comment] 2024-10-06 21:49
I think the problem is that Listeria doesn't like comments inside the query.

Removing the comments your list works fine. https://www.wikidata.org/w/index.php?title=Wikidata%3ASandbox&diff=2257149480&oldid=2254995176

I wonder whether that is a bug or just an undocumented feature.

**Comment by grimes2** [comment] 2024-10-07 10:39
Thank you! It seems Listeria doesn't like the apostrophe in "Commander's" comment.

**Comment by prototyperspective** [comment] 2024-10-09 10:04
If this is solved, please close the issue.

**Closed** 2024-10-13 01:33 UTC
