### ISSUE TITLE
ListeriaBot returns "Last line: ERROR: Login failed" and has only made one edit in the last 24 hours

### ISSUE THREAD

**Issue by Calistemon** [magnusmanske/listeria_rs#102] opened 2023-02-09 06:58 UTC
When I try to update Wikidata lists on the English Wikipedia, ListeriaBot returns "Last line: ERROR: Login failed" and does not update the lists. It has also only made one edit in the last 24 hours. Is there something wrong with the bot?

**Comment by geertivp** [comment] 2023-02-09 15:07
Same for me...

**Comment by CECSpecialistI** [comment] 2023-02-09 17:20
Same here.

**Comment by geertivp** [comment] 2023-02-09 18:03
Still the system returns an erroneous OK status, which is misleading, because it fails.

**Comment by M2k-dewiki** [comment] 2023-02-10 17:40
Also see
https://phabricator.wikimedia.org/T329380

**Comment by magnusmanske** [comment] 2023-02-11 17:44
Investigating. I can log in manually as ListeriaBot just fine. I believe it's been blocked on cywiki because editing without bot flag but that shouldn't affect the other wikis

**Comment by susannaanas** [comment] 2023-02-12 05:34
Just amplifying for my part as well. I have introduced a number of new Listeria lists in Meta, and they stopped updating on the 7th (?) with the same symptoms.

**Comment by geertivp** [comment] 2023-02-12 10:55
Confirmed: Problem seems to exist since 8 February?
https://guc.toolforge.org/?src=rc&by=date&user=ListeriaBot

**Comment by Calistemon** [comment] 2023-02-13 09:10
Still not working but the message when trying to update a page has now changed to "Last line: Return val: 101".

**Comment by magnusmanske** [comment] 2023-02-13 12:35
I have changed the bot login to oauth, as the "bot password" system did not appear to work correctly on WMF side (I could log in manually but not via API). Seems to edit but slowly. Keeping an eye.

**Comment by Calistemon** [comment] 2023-02-13 12:51
Indeed, its working again! Thank you. I missed this very helpful bot!

**Comment by magnusmanske** [comment] 2023-02-13 13:31
Looks stable now, I'll close this issue

**Closed by magnusmanske** 2023-02-13 13:31 UTC

**Comment by M2k-dewiki** [comment] 2023-03-16 13:43
Since yesterday, it returns

Last line:
Return val: 101

and the pages are not updated.

For example:

https://listeria.toolforge.org/index.php?action=update&lang=de&page=Wikipedia:Wikidata/Liste_k%C3%BCrzlich_verstorbener_Personen

https://de.wikipedia.org/wiki/Wikipedia%3AWikidata%2FListe_k%C3%BCrzlich_verstorbener_Personen

Thanks a lot!
