### ISSUE TITLE
List not updating

### ISSUE THREAD

**Issue by jkjkjkjkjk** [magnusmanske/listeria_rs#35] opened 2020-11-24 00:55 UTC
This listeria list is not updating:

https://www.wikidata.org/wiki/Wikidata%3ALists%2Fcorona_virus_deaths#Detailed_list

After trying "Manually update list" the result is "Done." and "Status: OK", but the list itself is not updated, while there are (unfortunately) new items (see the results of underlying query - https://w.wiki/h6i).

**Comment by Tagishsimon** [comment] 2020-11-26 11:12
Ditto https://en.wikipedia.org/wiki/Wikipedia%3AWikiProject_Women_in_Red%2FMissing_articles_by_occupation%2FPhilanthropists

It's still a widespread issue with WiR lists; very many not updating.

**Comment by ratonyi** [comment] 2020-12-02 14:39
Another example:
[https://www.wikidata.org/wiki/Wikidata:Wikivoyage/Lists/Embassies](url)

Command:

`./target/release/main 'www.wikidata.org' 'Wikidata:Wikivoyage/Lists/Embassies'`

Done.
Status: OK
--
Listeria bot status
8435. Wikidata:Wikivoyage/Lists/Embassies (OK; 2020-12-02 14:32:25)

**Comment by hanifalhusaini** [comment] 2020-12-06 12:13
https://id.wikipedia.org/wiki/Wikipedia%3AProyekWiki_studi_LGBT%2FBiografi_tokoh_LGBQ_yang_belum_ada and https://id.wikipedia.org/wiki/Wikipedia:ProyekWiki_Perempuan/Jumlah_pranala also did not update.

**Comment by hanifalhusaini** [comment] 2020-12-06 12:37
> 
> 
> https://id.wikipedia.org/wiki/Wikipedia%3AProyekWiki_studi_LGBT%2FBiografi_tokoh_LGBQ_yang_belum_ada and https://id.wikipedia.org/wiki/Wikipedia:ProyekWiki_Perempuan/Jumlah_pranala also did not update.

Both of the lists has updated now.

**Comment by jkjkjkjkjk** [comment] 2020-12-18 12:26
Changed to a bit more descriptive error "Killed by OS for overloading memory". Limiting the list works a bit.

**Comment by real68er** [comment] 2021-01-04 09:03
A manual update of [this query](https://www.wikidata.org/wiki/User:Sebastian_Wallroth/sandbox) returns _Killed by OS for overloading memory._

**Comment by jmreymond** [comment] 2021-01-22 05:34
almost all lists have this problem
https://fr.wikipedia.org/wiki/Projet:Wikidata/Listes/Anniversaire_aujourd%27hui
https://fr.wikipedia.org/wiki/Projet:Wikidata/Listes/D%C3%A9c%C3%A8s_r%C3%A9cents
https://fr.wikipedia.org/wiki/Projet:Wikidata/Listes/D%C3%A9c%C3%A8s_caus%C3%A9s_par_la_maladie_%C3%A0_coronavirus_2019

**Comment by magnusmanske** [comment] 2021-01-27 15:43
Closing this as many of the examples now work. I found one that still fails but is a duplicate of #53 and not a "general" failure.

**Closed by magnusmanske** 2021-01-27 15:43 UTC
