### ISSUE TITLE
Lists not updating

### ISSUE THREAD

**Issue by Tagishsimon** [magnusmanske/listeria_rs#13] opened 2020-11-16 13:11 UTC
For the following pages

a) the SPARQL runs within 60 seconds in WDQS

and the issue is

b) a Listeria manual update yields a status page saying 'all is good', but the pages are not, in fact, updated.

https://en.wikipedia.org/w/index.php?title=Wikipedia:WikiProject_Women_in_Red/Missing_articles_by_occpation/Actresses_-_country_unknown_%26_born_before_1973&action=history

https://en.wikipedia.org/w/index.php?title=Wikipedia:WikiProject_Women_in_Red/Missing_articles_by_occupation/Actresses_-_country_unknown_%26_born_after_1972&action=history

https://en.wikipedia.org/w/index.php?title=Wikipedia:WikiProject_Women_in_Red/Missing_articles_by_occupation/Painters_-_country_unknown_%26_born_before_1930&action=history

https://en.wikipedia.org/w/index.php?title=Wikipedia:WikiProject_Women_in_Red/Missing_articles_by_occupation/Painters_-_country_unknown_%26_born_after_1929&action=history

https://en.wikipedia.org/w/index.php?title=Wikipedia:WikiProject_Women_in_Red/Missing_articles_by_occupation/Politicians_-_Rest_of_world&action=history

**Comment by camelCaseNick** [comment] 2020-11-16 15:38
@Tagishsimon is this a duplicate of #12?

**Comment by Tagishsimon** [comment] 2020-11-16 17:49
Couple more; presume it's all the same issue.

https://en.wikipedia.org/w/index.php?title=Wikipedia:WikiProject_Women_in_Red/Missing_articles_by_occupation/Textile&action=history

https://en.wikipedia.org/w/index.php?title=Wikipedia:WikiProject_Women_in_Red/Missing_articles_by_dictionary/BDSW&action=history

**Comment by magnusmanske** [comment] 2020-11-19 17:11
- [1972 works](https://en.wikipedia.org/w/index.php?title=Wikipedia:WikiProject_Women_in_Red/Missing_articles_by_occupation/Actresses_-_country_unknown_%26_born_after_1972&action=history) now.
- [Rest of the world](https://en.wikipedia.org/w/index.php?title=Wikipedia:WikiProject_Women_in_Red/Missing_articles_by_occupation/Politicians_-_Rest_of_world&oldid=989534773) as well

There still seems to be some issue though. Investigating.

**Comment by magnusmanske** [comment] 2020-11-20 12:10
The first page does not appear to exist. The others have updated with V2

**Closed by magnusmanske** 2020-11-20 12:10 UTC
